### ISSUE TITLE
Not finding resource definition

### ISSUE THREAD

**Issue by dancesWithCycles** [bhavyakaria/Android#2]
Hi there,
thank you very much for the following tutorial I am working my way through at the moment.

https://medium.com/@bhavyakaria/step-by-step-guide-to-create-app-settings-using-preferences-in-android-part-1-fa470305b530

In the class SettingsActivity I have trouble finding the definition of the following resource.

android.R.id.home

Can anyone tell me where I should define this resource?

Cheers!

**Comment by bhavyakaria** [comment]
Hi there,
@derMitDemRadTanzt

Glad that my article helped you.

Regarding `android.R.id.home`, you don't need to define this resource anywhere. It is provided by Android for the back arrow button that you have on the action bar.

Check out this link, 
https://stackoverflow.com/questions/18718792/android-android-r-id-home-cant-be-resolved

Also, keep in mind the example isn't converted to AndroidX. So if your project has AndroidX then there might be some difference in file names and methods.

Regards,
Bhavya Karia

**Comment by dancesWithCycles** [comment]
Hi Bhavya Karia,
thank you very much for the prompt reply.

Cheers mate!
